import typing

from BaseClasses import Item
from typing import Dict

haakOffset = 135293000000

class ItemData(typing.NamedTuple):
    code: typing.Optional[int]
    progression: bool
    event: bool = False
    count: int = 1

item_table: Dict[str, ItemData] = {
    "KeyCard": ItemData(haakOffset, True, event=True),
    # Abilities
    "Glove": ItemData(haakOffset+1, True, count=1),
    "ProgressiveChargeAttack": ItemData(haakOffset+2, True, count=3),
    "ProgressiveSwordWaves": ItemData(haakOffset+3, True, count=2),
    "ProgressiveDash": ItemData(haakOffset+4, True, count=4),
    "Deflection": ItemData(haakOffset+5, True, count=1),
    "ProgressiveHook": ItemData(haakOffset+6, True, count=3),
    "ProgressiveDivingThrust": ItemData(haakOffset+7, True, count=2),
    "Rampage": ItemData(haakOffset+8, True, count=1),
    "ThrustUp": ItemData(haakOffset+9, True, count=1),
    "Glide": ItemData(haakOffset+10, True, count=1),
    "DashSlash": ItemData(haakOffset+11, True, count=1),
    "GasMask": ItemData(haakOffset+12, True, count=1),
    "Hacker": ItemData(haakOffset+13, True, count=1),
    # Upgrades
    "LifeShard": ItemData(haakOffset+14, True, count=22),
    "EnergyShard": ItemData(haakOffset+15, True, count=4),
    "AttackBoost": ItemData(haakOffset+16, True, count=4),
    "Hookspeed": ItemData(haakOffset+17, False, count=7),
    "Hooklength": ItemData(haakOffset+18, False, count=7),
    "CritRate": ItemData(haakOffset+19, False, count=7),
    "FirstAid": ItemData(haakOffset+20, True, count=2),
    "FirstAidEffect": ItemData(haakOffset+21, False, count=1),
    # Quest Items
    "HuntingCert": ItemData(haakOffset+22, False),
    "CatFood": ItemData(haakOffset+23, False),
    "Dessert Recipe": ItemData(haakOffset+24, True),
    "Metal Sniffer": ItemData(haakOffset+25, False),
    "East Passcard": ItemData(haakOffset+26, True),
    # Collectibles
    "Disk": ItemData(haakOffset+27, True, count=50),
    "DyeYellow": ItemData(haakOffset+28, False),
    "DyeRed": ItemData(haakOffset+29, False),
    "DyeGreen": ItemData(haakOffset+30, False),
    "DyePurple": ItemData(haakOffset+31, False),
    "DyeWhite": ItemData(haakOffset+32, False),
    "Tape Red": ItemData(haakOffset+33, False),
    "Tape Blue": ItemData(haakOffset+34, False),
    "Tape Yellow": ItemData(haakOffset+35, True),
    "TVAntenna": ItemData(haakOffset+36, False),
    "TVMotherBoard": ItemData(haakOffset+37, False),
    "TVPowerCord": ItemData(haakOffset+38, False),
    "PortableStereo": ItemData(haakOffset+39, True),
    "AlienLaptop": ItemData(haakOffset+40, False),
    "PhotoOfGenie": ItemData(haakOffset+41, False),
    "TheIntellectualsSpring": ItemData(haakOffset+42, False),
    "HuntingCert": ItemData(haakOffset+43, False),
    "Newspaper#1": ItemData(haakOffset+44, False),
    "Newspaper#2": ItemData(haakOffset+45, False),
    "Newspaper#3": ItemData(haakOffset+46, False),
    "Newspaper#4": ItemData(haakOffset+47, False),
    "Newspaper#5": ItemData(haakOffset+48, False),
    "Newspaper#6": ItemData(haakOffset+49, False),
    "Newspaper#7": ItemData(haakOffset+50, False),
    "Newspaper#8": ItemData(haakOffset+51, False),
    "Newspaper#9": ItemData(haakOffset+52, False),
    "Newspaper#10": ItemData(haakOffset+53, False),
    "EncryptedNote#1": ItemData(haakOffset+54, False),
    "EncryptedNote#2": ItemData(haakOffset+55, False),
    "EncryptedNote#3": ItemData(haakOffset+56, False),
    "SecretManual#1": ItemData(haakOffset+57, False),
    "SecretManual#2": ItemData(haakOffset+58, False),
    "SecretManual#3": ItemData(haakOffset+59, False),
    "Developers log #10": ItemData(haakOffset+60, False),
    "Developers log #20": ItemData(haakOffset+61, False),
    "Mysterious Flyer #1": ItemData(haakOffset+62, False),
    "Mysterious Flyer #2": ItemData(haakOffset+63, False),
    "Map of Brewery": ItemData(haakOffset+64, False),
    "Brewery Note": ItemData(haakOffset+65, False),
    # "Momoyama Elevation": ItemData(haakOffset+66, False),
    # "Momoyama Crisis": ItemData(haakOffset+67, False),
    "Report: Multi-Brain Connectors Research": ItemData(haakOffset+68, False),
    "Study of Hypnosis": ItemData(haakOffset+69, False),
    "Wasteland Reclaimer Poster": ItemData(haakOffset+70, False),
    "Hacking Device Manual": ItemData(haakOffset+71, False),
    "Daily Photo of Genie": ItemData(haakOffset+72, False),
    "Yoga Flyer": ItemData(haakOffset+73, False),
    "How to win over Pretty Girls": ItemData(haakOffset+7, False),
    "Report: Robot Virus": ItemData(haakOffset+75, False),
    "Torn Picture (Left)": ItemData(haakOffset+76, False),
    "Torn Picture (Right)": ItemData(haakOffset+77, False),
    "Letter of Commission": ItemData(haakOffset+78, False),
    "Report: Test Subject No. 36": ItemData(haakOffset+79, False),
    "Ms Lees Diary": ItemData(haakOffset+80, False),

    # Events
    "Vent1": ItemData(None, True, True),
    "Vent2": ItemData(None, True, True),
    "Vent3": ItemData(None, True, True),
    "Vent4": ItemData(None, True, True),
    "Vent5": ItemData(None, True, True),
    "Vent6": ItemData(None, True, True),
    "Vent7": ItemData(None, True, True),
    "Vent8": ItemData(None, True, True),
    "Vent9": ItemData(None, True, True),
    "Vent10": ItemData(None, True, True),
    "CleanVents": ItemData(None, True, True),
    "FattyDefeated": ItemData(None, True, True),
    "MoleGangLeaderDefeated": ItemData(None, True, True),
    "SamuraiDefeated": ItemData(None, True, True),
    "Victory": ItemData(None, True, True),
    # "sanho_ruins_room_35_terminal_door": ItemData(None, True, event=True),
    # "sanho_ruins_room_61_switch_door": ItemData(None, True, event=True),
    # "sanho_ruins_room_43_switch_door": ItemData(None, True, event=True),
    # "sanho_ruins_room_49_switch_door": ItemData(None, True, event=True),
}

event_item_pairs: Dict[str, str] = {
    "sanho_ruins_room_73_keycard": "KeyCard",
    "sanho_ruins_room_58_keycard": "KeyCard",
    "north_station_room_82_keycard": "KeyCard",
    "peoples_square_room_80_keycard": "KeyCard",
    "merlin_pit_vent1": "Vent1",
    "merlin_pit_vent2": "Vent2",
    "merlin_pit_vent3": "Vent3",
    "merlin_pit_vent4": "Vent4",
    "merlin_pit_vent5": "Vent5",
    "anthony_hill_vent6": "Vent6",
    "anthony_hill_vent7": "Vent7",
    "anthony_hill_vent8": "Vent8",
    "anthony_hill_vent9": "Vent9",
    "cleanvents": "CleanVents",
    # Bosses
    "fatty": "FattyDefeated",
    "molegangleader": "MoleGangLeaderDefeated",
    "samurai": "SamuraiDefeated",
    "gael": "Victory",
}
